### ISSUE TITLE
Fails to compile on OS X 10.7.5

### ISSUE THREAD

**Issue by scdwyer** [uaarg/telemetry-over-wifi#2]
Before the rework it compiled.

Gives the following error:
$ make
gcc -DUNIX  -Wall client.c -o client
Undefined symbols for architecture x86_64:
  "_socketConnection", referenced from:
      _main in ccmPgpkG.o
  "_msgTransit", referenced from:
      _main in ccmPgpkG.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
make: **\* [client] Error 1

@odeke-em any ideas?
